### ISSUE TITLE
With Immer - On<void> problem

### ISSUE THREAD

**Issue by daarxwalker** [cartant/ts-action#49]
Hi,
can't solve problem with mismatch generic type of On. State in actions is "any", but should be type of initialState. I also tried add State type to generic like r\<State\>, but nothing happens, still void. I had no such problem in the past.
Without using ts-action-immer, working great.

![Snímek obrazovky 2020-02-06 v 18 19 30](https://user-images.githubusercontent.com/26570413/73961909-c105b280-490d-11ea-8024-6e5d5444c235.png)
![Snímek obrazovky 2020-02-06 v 18 19 49](https://user-images.githubusercontent.com/26570413/73961912-c2cf7600-490d-11ea-94a5-30511dc2dc3c.png)
![Snímek obrazovky 2020-02-06 v 18 20 26](https://user-images.githubusercontent.com/26570413/73961914-c3680c80-490d-11ea-962f-3744847d2ddf.png)

**Packages versions:**
"immer": "^5.3.4",
"ts-action": "^11.0.0",
"ts-action-immer": "^3.0.1",
"redux": "^4.0.5",
"typescript": "3.6.5",

If u need more info, can provide anything. Thanks :)

**Comment by cartant** [comment]
It seems that it's the TypeScript version that's the problem. Works fine with 3.7. However, if I change the repo's TypeScript version to 3.6.5, the tests fail with the same error that you are seeing.

That seems weird because the last code changes that I made were months ago and the test passed when using an earlier version of 3.6:

https://github.com/cartant/ts-action/blob/f3647a763bac6425fa2ebdfee451fcbe2cb6cab9/packages/ts-action-immer/package.json#L23

https://github.com/cartant/ts-action/blob/f3647a763bac6425fa2ebdfee451fcbe2cb6cab9/packages/ts-action-immer/source/reducer-spec.ts#L56-L65

**Comment by cartant** [comment]
When using TS `3.6.5`, I also see this error in the tests:

```
source/reducer-spec.ts:40:28 - error TS2315: Type 'Draft' is not generic.

40       const func = (state: Draft<{}>, action: typeof both.actions) => ({});
```

`Draft` is clearly generic, so I'm inclined to believe that there is something in the `immer` types - a new version was released since I last made code changes - that requires TS 3.7.

That's as far as I'm going to take this, now, as it doesn't look like the problem is caused by this package, to me.

**Comment by daarxwalker** [comment]
You're right. TS 3.7 and higher working. Thanks for check.
Keep it up with good work! :) 👍

**Comment by cartant** [comment]
No worries. I might have a look to see what changed in immer, sometime. I'm very surprised that it works with 3.7 but breaks with 3.6.
